[package]
name = "unicode-formatter"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
directories = "6.0.0"
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"]}
serde_derive = "1.0.218"
toml = "0.8.20"
